backend:
  name: github
  repo: Turutupa/blog

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    sortableFields: ["date", "title", "Updated On", "Description"]
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - {
          name: tags,
          label: Tags,
          widget: list,
          allow_add: true,
          label_singular: Add tag,
          max: 4,
          min: 1,
          default: ["random", "life"],
        }
      - {
          widget: relation,
          name: related_posts,
          label: Related Posts,
          required: false,
          multiple: true,
          hint: Other related posts,
          collection: blog,
          valueField: title,
          searchFields: ["title"],
          displayFields: ["title"],
        }
      - { name: body, label: Body, widget: markdown }

  - name: activity
    label: activity
    folder: content/activity
    create: true
    sortableFields: ["date", "title"]
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
