export const operand = "operand"
export const division = "÷"
export const minus = "-"
export const dot = ","
export const times = "x"
export const plus = "+"
export const equal = "="
export const integer = "integer"
export const clear = "clear"
export const ac = "C"
export const ce = "CE"
export const gameModes = "M"
export const zero = "0"
export const one = "1"
export const two = "2"
export const three = "3"
export const four = "4"
export const five = "5"
export const six = "6"
export const seven = "7"
export const eight = "8"
export const nine = "9"
// 13 chars in a row * 4 rows
export const maxChars = 13 * 4
